# Generated by Django 4.2.3 on 2023-07-18 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Mammifères', 'Mammifères'), ('Oiseaux', 'Oiseaux'), ('Poissons', 'Poissons')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('ageMax', models.IntegerField()),
                ('avgWeight', models.FloatField()),
                ('nomS', models.CharField(max_length=120)),
                ('typeAnimal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='safarioApp.animaltype')),
            ],
        ),
    ]
