# Generated by Django 4.2.3 on 2023-07-18 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safarioApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='categorieAnimal',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='safarioApp.animaltype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animal',
            name='typeAnimal',
            field=models.CharField(max_length=100),
        ),
    ]
