# Generated by Django 4.2.3 on 2023-07-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safarioApp', '0002_animal_categorieanimal_alter_animal_typeanimal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='avgWeight',
            field=models.CharField(max_length=20),
        ),
    ]
